version: 0.2
env:
  variables:
    REACT_APP_API_BASE_URL: $REACT_APP_API_BASE_URL
    REACT_APP_LINKEDIN_CLIENT_ID: $REACT_APP_LINKEDIN_CLIENT_ID
    REACT_APP_LINKEDIN_CALLBACK_URI: $REACT_APP_LINKEDIN_CALLBACK_URI
    REACT_APP_REDDIT_CLIENT_ID: $REACT_APP_REDDIT_CLIENT_ID
    REACT_APP_REDDIT_CALLBACK_URI: $REACT_APP_REDDIT_CALLBACK_URI
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing project dependencies...
      - yarn install
  build:
    commands:
      - echo Initiating build...
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: build
